apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: frontend-api
  namespace: production
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
        component: frontend-api
        environment: production
    spec:
      containers:
      - name: frontend-api
        image: fbeltrao.azurecr.io/frontendapi:51
        ports:
        - containerPort: 80
