apiVersion: v1
kind: Service
metadata:
  name: frontend-production-web
  namespace: production  
  labels:
    app: frontend
    component: frontend-web
    environment: production
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
  selector:
    component: frontend-web
    environment: production