apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: frontend-production-web
  namespace: production
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend        
        component: frontend-web
        environment: production        
    spec:
      containers:
      - name: frontend-api
        image: fbeltrao.azurecr.io/frontendweb:41
        ports:
        - containerPort: 80